In [ ]:
#Jonathan Pak
# 2/21/2018
# jpak@scu.edu

## In-class Exercise 3## 
** 02.21.18**
<br>
**Multinomial Naive Bayes** using scikit-learn

In [35]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()

Please take 5 to 10 mins to review [20 news gropups text dataset](http://scikit-learn.org/stable/datasets/index.html#the-20-newsgroups-text-dataset). It is important to know and understand your data before you do anything with it! The link will give you more pointers on how to proceed with data engineering component. 

In [36]:
# using the data from sklearn datasets
from sklearn.datasets import fetch_20newsgroups

data = fetch_20newsgroups()


In [37]:
# print the list of target_names (or different classes/categories)
from pprint import pprint
newsgroups_train = fetch_20newsgroups(subset='train')
pprint(list(newsgroups_train.target_names)) 

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']


For simplicity here, we will select just a few of these categories, and download the training and testing set:

In [38]:
cats = ['talk.religion.misc', 'soc.religion.christian',
              'sci.space', 'comp.graphics'] # I have done this for you here!

In [39]:
# Now take the above subset of categories, and fetch 'train' and 'test' data into two different variable
newsgroups_train = fetch_20newsgroups(subset='train', categories=cats)
newsgroups_test = fetch_20newsgroups(subset='test', categories=cats)

In [40]:
# Print a representative entry from the data that you have fetched
print(newsgroups_train.data[0])

From: jono@mac-ak-24.rtsg.mot.com (Jon Ogden)
Subject: Re: Losing your temper is not a Christian trait
Organization: Motorola LPA Development
Lines: 26

In article <Apr.23.02.55.47.1993.3138@geneva.rutgers.edu>, jcj@tellabs.com
(jcj) wrote:

> I'd like to remind people of the withering of the fig tree and Jesus
> driving the money changers et. al. out of the temple.  I think those
> were two instances of Christ showing anger (as part of His human side).
> 
Yes, and what about Paul saying:

26 Be ye angry, and sin not: let not the sun go down upon your wrath:
(Ephesians 4:26).

Obviously then, we can be angry w/o sinning.

Jon

------------------------------------------------
Jon Ogden         - jono@mac-ak-24.rtsg.mot.com
Motorola Cellular - Advanced Products Division
Voice: 708-632-2521      Data: 708-632-6086
------------------------------------------------

They drew a circle and shut him out.
Heretic, Rebel, a thing to flout.
But Love and I had the wit to win;
We drew a circle and 

In order to use this data for machine learning, we need to be able to convert the content of each string into a vector of numbers. For this we will use the TF-IDF vectorizer, and create a pipeline that attaches it to a multinomial naive Bayes classifier:

In [41]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline
from sklearn import metrics

model = make_pipeline(TfidfVectorizer(), MultinomialNB())

In [42]:
# Your task is to take few minutes again to review the pipeline
# How would you vectorize, and then use the data to train your model


With this pipeline, we can apply the model to the training data, and predict labels for the test data:

In [43]:
# train the model
model.fit(newsgroups_train.data, newsgroups_train.target)
# predict the labels of the tes
prediction = model.predict(newsgroups_test.data)

                               
    

Now that we have predicted the labels for the test data, we can evaluate them to learn about the performance of the estimator.
For example, here is the confusion matrix between the true and predicted labels for the test data:

In [46]:
# plot the confusion matrix between the true and predicted labels for the test data 

from sklearn.metrics import confusion_matrix
# TODO
Confusion_Matrix =  confusion_matrix(newsgroups_test.target, prediction)
print newsgroups_test.target_names
print Confusion_Matrix

['comp.graphics', 'sci.space', 'soc.religion.christian', 'talk.religion.misc']
[[344  13  32   0]
 [  6 364  24   0]
 [  1   5 392   0]
 [  4  12 187  48]]


Evidently, even this very simple classifier can successfully separate space talk from computer talk, but it gets confused between talk about religion and talk about Christianity.
This is perhaps an expected area of confusion!The very cool thing here is that we now have the tools to determine the category for any string, using the `predict()` method of this pipeline.

Write  a quick utility function that will return the prediction for a single string:

In [58]:
# write a function like this
def predict_category(s, train=newsgroups_train, model=model):
    prediction = model.predict([s])[0]
    return newsgroups_test.target_names[prediction]

Let's try it out:

In [59]:
# we can call the function as shown:
predict_category('sending a payload to the ISS') 
# the output will be the predicted category 'sci.space'

'sci.space'

In [60]:
# another example
predict_category('discussing islam vs atheism')
# the output will be 'soc.religion.christian'

'soc.religion.christian'

In [61]:
#another example
predict_category('determining the screen resolution')
# the output will be 'comp.graphics'

'comp.graphics'